[workspace]
resolver = "2"
members = [
    "crates/pmx",
    "crates/pmx-modules",
    "crates/pmx-sdk",
    "crates/pmx-modules/handle-growth",
    "crates/pmx-modules/json",
    "crates/pmx-modules/lsof",
    "crates/pmx-modules/memory-growth",
    "crates/pmx-modules/perfetto",
    "crates/pmx-modules/process-basic",
    "crates/pmx-modules/process-restart",
    "crates/pmx-modules/pstack",
    "crates/pmx-modules/top",
]
